# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-28 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='category',
            field=models.CharField(choices=[('O', 'Owner'), ('A', 'Administrator'), ('C', 'Coordinator'), ('I', 'Intern'), ('V', 'Volunteer')], default='V', max_length=2),
            preserve_default=False,
        ),
    ]
