# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-02 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user'),
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('title', 'organization')]),
        ),
    ]
